### ISSUE TITLE
报下面的错，请问怎么解决

### ISSUE THREAD

**Issue by ycrao** [waylybaye/XcodeCleaner#7]
```bash

React packager ready.

Loading dependency graph...
Bundling `index.macos.js`  ░░░░░░░░░░░░░░░░  0.0% (0/1)2017-10-16 14:09 node[30976] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-10-16 14:09 node[30976] (FSEvents.framework) FSEventStreamStart: register_w ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1026:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
Loading dependency graph...
Bundling `index.macos.js`  ░░░░░░░░░░░░░░░░  0.0% (0/1)~
Process terminated. Press <enter> to close the window
```

**Comment by waylybaye** [comment]
duplicated with #3
